from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class IoTEquipment(Base):
    """
    Stores the registered Smart Gym equipment and its
    latest known resistance/state.
    """

    __tablename__ = "iot_equipment"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    equipment_id: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False,
        index=True,
    )

    equipment_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    current_resistance: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )


class IoTTelemetry(Base):
    """
    Stores historical telemetry received from Smart Gym
    equipment.
    """

    __tablename__ = "iot_telemetry"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    equipment_id: Mapped[int] = mapped_column(
        ForeignKey("iot_equipment.id"),
        nullable=False,
        index=True,
    )

    resistance_level: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    repetitions: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    performance_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    heart_rate: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    fatigue_level: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    recorded_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )


class IoTCommand(Base):
    """
    Stores commands generated by the Smart Gym AI
    controller.
    """

    __tablename__ = "iot_commands"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    equipment_id: Mapped[int] = mapped_column(
        ForeignKey("iot_equipment.id"),
        nullable=False,
        index=True,
    )

    action: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )

    value: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    reason: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )