"""add emotion tracking to chat messages

Revision ID: 0928d02bbd2c
Revises: dcaefc0a76e6
Create Date: 2026-09-13 01:37:55.117963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0928d02bbd2c'
down_revision: Union[str, None] = 'dcaefc0a76e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('emotion', sa.String(length=50), nullable=True))
    op.add_column('chat_messages', sa.Column('motivation_level', sa.String(length=30), nullable=True))
    op.add_column('chat_messages', sa.Column('emotion_confidence', sa.Float(), nullable=True))
    op.add_column('chat_messages', sa.Column('strategy', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'strategy')
    op.drop_column('chat_messages', 'emotion_confidence')
    op.drop_column('chat_messages', 'motivation_level')
    op.drop_column('chat_messages', 'emotion')
    # ### end Alembic commands ###
