"""create iot equipment telemetry and commands

Revision ID: 72a6c1482fd3
Revises: 0928d02bbd2c
Create Date: 2026-09-13 09:15:06.970918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a6c1482fd3'
down_revision: Union[str, None] = '0928d02bbd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('current_resistance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_equipment_equipment_id'), 'iot_equipment', ['equipment_id'], unique=True)
    op.create_index(op.f('ix_iot_equipment_id'), 'iot_equipment', ['id'], unique=False)
    op.create_table('iot_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['iot_equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_commands_created_at'), 'iot_commands', ['created_at'], unique=False)
    op.create_index(op.f('ix_iot_commands_equipment_id'), 'iot_commands', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_iot_commands_id'), 'iot_commands', ['id'], unique=False)
    op.create_table('iot_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('resistance_level', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=False),
    sa.Column('fatigue_level', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['iot_equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_telemetry_equipment_id'), 'iot_telemetry', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_iot_telemetry_id'), 'iot_telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_iot_telemetry_recorded_at'), 'iot_telemetry', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iot_telemetry_recorded_at'), table_name='iot_telemetry')
    op.drop_index(op.f('ix_iot_telemetry_id'), table_name='iot_telemetry')
    op.drop_index(op.f('ix_iot_telemetry_equipment_id'), table_name='iot_telemetry')
    op.drop_table('iot_telemetry')
    op.drop_index(op.f('ix_iot_commands_id'), table_name='iot_commands')
    op.drop_index(op.f('ix_iot_commands_equipment_id'), table_name='iot_commands')
    op.drop_index(op.f('ix_iot_commands_created_at'), table_name='iot_commands')
    op.drop_table('iot_commands')
    op.drop_index(op.f('ix_iot_equipment_id'), table_name='iot_equipment')
    op.drop_index(op.f('ix_iot_equipment_equipment_id'), table_name='iot_equipment')
    op.drop_table('iot_equipment')
    # ### end Alembic commands ###
