"""create workout sessions table

Revision ID: ad0cc6e627bf
Revises: 36c4596fa73d
Create Date: 2026-09-12 22:26:47.625226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0cc6e627bf'
down_revision: Union[str, None] = '36c4596fa73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=50), nullable=False),
    sa.Column('total_repetitions', sa.Integer(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('best_frame_score', sa.Float(), nullable=False),
    sa.Column('worst_frame_score', sa.Float(), nullable=False),
    sa.Column('depth_score', sa.Float(), nullable=False),
    sa.Column('posture_score', sa.Float(), nullable=False),
    sa.Column('control_score', sa.Float(), nullable=False),
    sa.Column('average_repetition_score', sa.Float(), nullable=False),
    sa.Column('best_repetition_score', sa.Float(), nullable=False),
    sa.Column('worst_repetition_score', sa.Float(), nullable=False),
    sa.Column('rating', sa.String(length=30), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_exercise'), 'workout_sessions', ['exercise'], unique=False)
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_exercise'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
